spring:
  application:
    name: kedargit
  datasource:
    url: jdbc:postgresql://localhost:5432/kedarpgdb
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

